/**:
    ros__parameters:
        image_transport: raw    # image format
        family: 36h11           # tag family name
        size: 0.068             # tag edge size in meter
        max_hamming: 0          # maximum allowed hamming distance (corrected bits)

        # see "apriltag.h" 'struct apriltag_detector' for more documentation on these optional parameters
        detector:
            threads: 2          # number of threads
            decimate: 1.0       # decimate resolution for quad detection
            blur: 0.0           # sigma of Gaussian blur for quad detection
            refine: 1           # snap to strong gradients
            debug: 0            # write additional debugging images to current working directory
        tag:
          ids:    [0, 1, 2, 3]         # tag IDs for which to publish transform
          frames: [ta_0, ta_1, ta_2, ta_3]   # frame names
          sizes:  [0.16, 0.06, 0.16, 0.06]     # tag-specific edge size, overrides the default 'size'
        bundle:
          name: dock_bundle
          ids: [0, 1, 2, 3]
          layout: # {X_POS, Y_POS, Z_POS, QUAT_W_VAL, QUAT_X_VAL, QUAT_Y_VAL, QUAT_Z_VAL}
            tag_0: [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0] #  left big tag -- origin
            tag_1: [0.21, 0.08, 0.0, 1.0, 0.0, 0.0, 0.0] # left small tag
            tag_2: [0.41, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0] #  right big tag
            tag_3: [0.31, 0.08, 0.0, 1.0, 0.0, 0.0, 0.0] # right small tag
